#!/bin/sh
FILE="VERSION2"
# BVER=`cat $FILE | cut -d . -f 1,2` 
VERSION=`cat $FILE | cut -d . -f 1`
VERSION=$(($VERSION+1))
echo -n $VERSION. > $FILE.tmp
cat $FILE | cut -d . -f 2,3,4 >>$FILE.tmp
mv -f $FILE.tmp $FILE
